@module: development-environment
@version: 1.0.0
@priority: High

overview: |
  Comprehensive specification for the development environment setup,
  ensuring consistent development experience across the team.

prerequisites:
  node:
    version: ">=22.0.0"
    package_manager: "npm >=10.0.0"
    global_packages:
      - "typescript"
      - "vite"
      - "vitest"

  git:
    version: ">=2.30.0"
    configuration:
      core.autocrlf: "true"
      core.longpaths: "true"

  ide:
    recommended: "Cursor"
    extensions:
      - "dbaeumer.vscode-eslint"
      - "esbenp.prettier-vscode"
      - "bradlc.vscode-tailwindcss"
      - "runem.lit-plugin"

development_server:
  frontend:
    command: "npm run dev"
    port: 3000
    hot_reload: true

  backend:
    command: "npm run dev:backend"
    port: 8000
    watch: true

  storybook:
    command: "npm run storybook"
    port: 6006

  documentation:
    command: "npm run docs"
    port: 8082

code_quality:
  linting:
    tool: "eslint"
    config: ".eslintrc.js"
    autofix: true

  formatting:
    tool: "prettier"
    config: ".prettierrc"
    autofix: true

  type_checking:
    tool: "typescript"
    config: "tsconfig.json"
    strict: true

testing:
  unit:
    tool: "vitest"
    watch: true
    coverage: true

  e2e:
    tool: "playwright"
    browsers:
      - "chromium"
      - "firefox"
      - "webkit"

  component:
    tool: "storybook"
    stories: "src/**/*.stories.ts"

build_process:
  development:
    tool: "vite"
    mode: "development"
    sourcemaps: true
    optimization: false

  production:
    tool: "vite"
    mode: "production"
    sourcemaps: false
    optimization: true

debugging:
  browser:
    devtools: true
    sourcemaps: true
    extensions:
      - "Redux DevTools"
      - "Lit DevTools"

  node:
    inspector: true
    breakpoints: true
    console: true

version_control:
  branching:
    main: "main"
    development: "develop"
    feature: "feature/*"
    bugfix: "bugfix/*"

  commit_hooks:
    pre_commit:
      - "lint-staged"
      - "type-check"
    pre_push:
      - "test"

environment_variables:
  development:
    file: ".env.development"
    required:
      - "DATABASE_URL"
      - "API_KEY"

  test:
    file: ".env.test"
    required:
      - "DATABASE_URL"
      - "TEST_API_KEY"

documentation:
  setup:
    tool: "mkdocs"
    theme: "dracula"
    auto_deploy: true

  api:
    tool: "typedoc"
    output: "docs/api"

  storybook:
    stories: true
    docs: true
    addons:
      - "@storybook/addon-docs"
      - "@storybook/addon-controls"
