site_name: FARM Stack Documentation
site_description: Documentation for the FARM Stack Boilerplate
site_author: Falkicon
site_url: https://falkicon.github.io/farm

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: true
  - tables

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Development: getting-started/development.md
    - Project Structure: getting-started/project-structure.md
  - Frontend:
    - Overview: frontend/index.md
    - Components:
      - Guidelines: frontend/components/guidelines.md
      - Fluent UI:
        - Overview: frontend/components/fluent/overview.md
    - State Management: frontend/state-management.md
    - Routing: frontend/routing.md
  - Backend:
    - Overview: backend/index.md
    - API Guidelines: backend/api/guidelines.md
    - Database: backend/database.md
  - Configuration: configuration/index.md
  - Development:
    - Workflow: development/workflow.md
  - Security: security/index.md
  - Performance: performance/index.md
  - Testing: testing/index.md
  - Deployment: deployment/index.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Falkicon/farm
    - icon: fontawesome/brands/discord
      link: https://discord.gg/farm-stack
