openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: A test API specification

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /test:
    get:
      summary: Test endpoint
      operationId: getTest
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Test successful"

components:
  schemas:
    TestResponse:
      type: object
      properties:
        message:
          type: string
          description: Response message

security:
  - {}  # No security requirements for test endpoint

tags:
  - name: test
    description: Test operations
